### ISSUE TITLE
Custom SMTP server via ADSL does not work

### ISSUE THREAD

**Issue by premoli** [Raikia/FiercePhish#15]
Custom SMTP server via ADSL does not work:

FirePhish Follow Up Items:
     1. Go to http://ADSL_IP/ to use FirePhish! (or http://127.0.0.1/ if you used a domain name)

   DNS Changes:
     1. A record for '@' point to 'ADSL_IP'
     2. A record for 'www' point to 'ADSL_IP'
     3. TXT record for 'mail._domainkey' with text: v=DKIM1; k=rsa;  p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDVRHFPG0uRBWhDPVzFj548neBdTSr5LILFy1LTE2A7Shc2eSFz0zFAKyLzQheP2e9p22TVBgbOqRqPG+44FPWLtokJrGtaBlMDh/w9g+3RbziJmjZilPXkdTJrXh1T+jznzWowoZ5LtKomnGOB9R95ix2S9HQ/94DFHeJJ0v0GLwIDAQAB
     4. A record for 'mail' point to 'ADSL_IP'
     5. MX record point to 'mail' subdomain (or MXE record pointing to ADSL_IP)
     6. TXT record for '@' with text: v=spf1 a mx a:mail.localhost a:localhost ip4:ADSL_IP ~all
     7. TXT record for '_dmarc' with text: v=DMARC1; p=none

**Comment by premoli** [comment]
Receiver Name	Receiver Email	Sender Name	Sender Email	Subject	Status	Campaign	Created At	Updated At
Fabio	my@email	test	test@test.com	Teste	Sent	None	Jan 9, 2017 @ 8:52:00 am	Jan 9, 2017 @ 8:52:03 am
Premoli	my@email	Obione Kanobi	Obione@Kanobi.com	Teste	Sent	None	Jan 9, 2017 @ 8:50:26 am	Jan 9, 2017 @ 8:50:27 am

Show as Sent, but not receive

**Comment by Raikia** [comment]
Check ```/var/log/mail.log``` to see what is happening on the mailserver side.  When it shows "Sent", that means the email was successfully handed off to the smtp server, so now you have to look at that log to see if it was rejected by the receiving mail server.  Post your ```/var/log/mail.log``` file (or email it to raikiasec@gmail.com) for me to take a look at.

I also see you sent the emails from @test.com and @kanobi.com.  If your DNS entries are not properly configured, it will be sent to the spam folder.  Make sure they are properly configured too!

I'll wait until you get back to me with the mail.log file

**Comment by Raikia** [comment]
Not sure if it was related to this, but there was an installer bug where if you provided "127.0.0.1" to the email domain question, postfix would fail to install and no emails could be sent.  I've fixed that now and the new installer does much better error detection.  Will be in next release

**Comment by Raikia** [comment]
This was included in the [v1.2.0 release](https://github.com/Raikia/FiercePhish/releases/tag/v1.2.0).  Issue resolved.
