### ISSUE TITLE
Feature request: Send test e-mails

### ISSUE THREAD

**Issue by GitHipster** [Raikia/FiercePhish#18]
Feature request: Send test e-mails

**Comment by Raikia** [comment]
Is this different from "[Email Simple Send](https://github.com/Raikia/FiercePhish/wiki/Feature:-Email-Simple-Sending)"?  That can easily be used as a test email system.

**Comment by GitHipster** [comment]
I was under the impression that the Email Simple Send action would somehow end up in the database under a campaign log somewhere. If not than it's basically the same.

**Comment by Raikia** [comment]
Using the Email Simple Send will only have the email show up under Email Log, but it will be unassociated with any campaign.  So it really works for this purpose.  Reopen issue if you disagree and want a different feature!
