### ISSUE TITLE
UUID of target_users do not match the [uid] values embedded via the email template

### ISSUE THREAD

**Issue by cobbr** [Raikia/FiercePhish#24]
Is the [uid] value that gets placed into each email from the email template stored anywhere in the backend database? It doesn't appear to match the UUID value of the corresponding target_user.

It would be useful for tracking link clicks to be able to access this value externally from FiercePhish. I don't mind implementing this behavior myself, I just wanted to be sure that I'm not missing something.

**Comment by Raikia** [comment]
Right, so this is something that is already in the process of being fixed.  The UUID of a user is _not_ the same as the UUID sent in an email.  It changes per campaign.  So the UUID of the target user is not actually sent in an email, its used in combination with the campaign_id to generate a **new** UUID.  Look at your campaign details and you will see the actual uuids sent and which user it corresponds to.

But yes, I am planning on changing how this is being saved for easier understanding.

**Comment by Raikia** [comment]
To answer your question: No, the uuid used in the email is _not_ currently stored in the database.  But that will change in the dev branch within the next 24-48 hours :-)

**Comment by cobbr** [comment]
Awesome! Thanks for the quick response. So, just to be clear, you are changing the behavior to use the target_user UUID in the email, or adding a UID field for emails in the database?

**Comment by Raikia** [comment]
There will be a UID field in the "emails" table.

**Comment by Raikia** [comment]
The dev branch now has the UUID changes you requested.  It will be merged in to master after testing.

**Comment by cobbr** [comment]
Thanks!

**Comment by Raikia** [comment]
Completed, committed, and merged into master.
