### ISSUE TITLE
Feature request: Add [firstname] variable

### ISSUE THREAD

**Issue by GitHipster** [Raikia/FiercePhish#25]
Feature request: Add [firstname] variable

**Comment by Raikia** [comment]
I actually noticed this was missing.  It's in the dev branch already and will be merged into master after I'm done testing the changes :-) 366e305b

**Comment by Raikia** [comment]
Completed, committed, and merged into master.

**Comment by GitHipster** [comment]
Thanks, i updated FP and it's now available!
