### ISSUE TITLE
Feature request: Two factor authentication admin portal (RADIUS)

### ISSUE THREAD

**Issue by GitHipster** [Raikia/FiercePhish#26]
Feature request: Two factor authentication admin portal (RADIUS)

**Comment by Raikia** [comment]
I can't do RADIUS 2-FA/authentication for now because it would require a fairly significant rewrite of the authentication mechanism.  That said, I have implemented Google 2-FA that you can enable by going to "Edit Profile"

**Comment by Raikia** [comment]
Completed, committed, and merged into master.

**Comment by GitHipster** [comment]
Great! After the update Google 2FA is available!
