### ISSUE TITLE
Feature request: Upgrade function via web interface

### ISSUE THREAD

**Issue by GitHipster** [Raikia/FiercePhish#30]
Feature request: Upgrade function via web interface

**Comment by Raikia** [comment]
This is a pretty good idea.  I will look into adding it.

**Comment by Raikia** [comment]
This was included in the [v1.2.0 release](https://github.com/Raikia/FiercePhish/releases/tag/v1.2.0).  Issue resolved.

**Comment by GitHipster** [comment]
Great, thanks!
