### ISSUE TITLE
DataTables error when viewing/adding targets after uri prefix is set

### ISSUE THREAD

**Issue by feemjmeem** [Raikia/FiercePhish#31]
After a new installation on Ubuntu 16.04.1 LTS, when the FiercePhish prefix has been changed via the web interface, listing targets causes this pop-up to appear:

`DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

Corresponding apache log:

`<snip> - - [12/Jan/2017:16:14:00 +0000] "POST /a/b/c/ajax/targetuser/list HTTP/1.1" 500 5084 "http://<snip>/a/b/c/targets" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"`

This error does not occur after a new installation if the FiercePhish prefix has not been changed.

**Comment by Raikia** [comment]
Excellent, thanks for this bug report, this actually saved a lot of headache down the road :-).  Fixed and will be merged into master shortly

**Comment by Raikia** [comment]
Merged in to master now
