### ISSUE TITLE
Unable to navigate

### ISSUE THREAD

**Issue by reynas** [Raikia/FiercePhish#33]
Possibly a dumb question, but I just installed FiercePhish locally on a freshly installed Ubuntu 16, and when clicking something in the left menu, nothing happens. In other words, I'm unable to navigate through the site without manually filling in the URL's.

**Comment by Raikia** [comment]
I will investigate this and get back to you shortly!  Is it a fresh install?

**Comment by Yikez978** [comment]
Yes, we are having the same issue on a fresh install today.

**Comment by reynas** [comment]
cool thanks.
Yes,
1. I downloaded an ubuntu 16 iso file. 
2. Did an easy install on vmware
3. Followed automated installation Method #2
4. Used the firefox browser on the ubuntu

The links are present, but the dropdowns are not working?
Note that I used the local IP 192.168.x.x as "domain", not that this should make a difference

**Comment by Raikia** [comment]
I believe a dependency broke in master and that is what is causing this.  I fixed it in the dev branch but I'm now trying it in master and will be hotfixed shortly with an update solution here.

73eea2b is the commit in dev branch.  Working on seeing if that is the same issue in master.  Should know in the next 15 minutes.

**Comment by Raikia** [comment]
Bug confirmed, a dependency removed a one of its dependencies and broke master branch.  I fixed it and pushed a hotfix.

Update solution for you:

```
cd /var/www/fiercephish
git pull origin master
bower install --allow-root
```

After that, you should be good to go.

**Comment by reynas** [comment]
Fixed, thank you for the swift reply and fix!
