### ISSUE TITLE
SMTP Gmail

### ISSUE THREAD

**Issue by cintainfinita** [Raikia/FiercePhish#36]
Hello! I'm using Gmail's SMTP, port 587, TLS config on FiercePhish (or at least I'm trying).

I'm not being able to send single emails or by starting a campaign.. basically I'm getting this:

Error: Address in mailbox given [] does not comply with RFC 2822, 3.6.2.

I think that's the problem.. not because of using Google's SMTP (since I can use it in a Python script.. no 2FA on the account I'm configuring to send the emails from)

It seems that some variables are not getting the "TO:" email because it looks "blank"...

Any help? Fresh Ubuntu 16.04 Installation, FiercePhish Remote Installation the only thing running...

Thank you!

**Comment by Raikia** [comment]
I will look into this, I've honestly not tried with Google's SMTP servers.

**Comment by Raikia** [comment]
This took me a surprisingly long time to figure out, but its completely unrelated to Google's SMTP server.  The "BCC" part is breaking.

For a quick fix, open your ".env" file and change:
     MAIL_BCC_ALL=
to
     MAIL_BCC_ALL=null

Then run "php artisan config:cache".  This will resolve your problem.

A permanent solution will be in the next release.

**Comment by cintainfinita** [comment]
Perfect! I will try this tomorrow and let you know.

Thanks a lot!

**Comment by Raikia** [comment]
Did my suggestion resolve it?

**Comment by cintainfinita** [comment]
Haven't tried it yet, sorry.

**Comment by ziflar** [comment]
@cintainfinita 
 @Raikia 
i've tried and didn't work 
also didn't work with mailgun
thx to test it and edit 
@+

**Comment by Raikia** [comment]
This has been fixed in v1.2.1.  You can use the update script to update properly.  Please let me know if this did not fix your specific issue and I will reopen the issue ticket.
