### ISSUE TITLE
FiercePhish dont start

### ISSUE THREAD

**Issue by dnkls** [Raikia/FiercePhish#40]
I use auto install method , all installation run perfect:

http://i.imgur.com/flKUzSd.png

...but admin panel dont start:

http://i.imgur.com/yXH5J2q.png

**Comment by Raikia** [comment]
It looks like PHP wasn't installed properly...?

Try running ```./install.sh -v | tee log.txt```.  If it still doesn't work, send me log.txt.

**Comment by Raikia** [comment]
Closed as probably duplicate of #35
