### ISSUE TITLE
User miscount when target created from Simple Send

### ISSUE THREAD

**Issue by ad0nis** [Raikia/FiercePhish#43]
Users created by Simple Send are not appropriately counted in the UI if they are then later added to a campaign.

Repro steps:
- Use Simple Send to send a message to a test email address
- All Lists > Add a list
- [During list creation, the user from the earlier test should be visible. Add them to the list.]
- Add another user to the list.
- Create a campaign.
- Send test message to the two-user list.
- Observe that the Dashboard shows a user count of 1 despite 2 emails going outbound.

**Comment by Raikia** [comment]
Good catch, this is actually a bug elsewhere.  When you send a "simple send"email, it creates a hidden TargetUser for use on the back-end.  It should not be assignable to a list at all (which is where the bug resides).  To make the TargetUser unhidden, you need to add it under "All Targets", which is when it can then be used in a list and a campaign.

**Comment by Raikia** [comment]
This has been fixed and pushed to master.  Thanks for the bug report.  It will be included in the next auto-update release (or if you completely fresh install)
