### ISSUE TITLE
ADD IP rotation

### ISSUE THREAD

**Issue by drivebyde** [Raikia/FiercePhish#53]
Hey dude!
Thank you so much for this wonderfull tool!!!!!
But pls install a IP Rotation Plugin.
Maybe priv per BTC?

Greetz from GER

**Comment by Raikia** [comment]
What?  Please explain more

**Comment by Raikia** [comment]
Closed due to no information

**Comment by BirdBolt** [comment]
If I understand correctly, what this person was asking about was the inclusion of a tool to continously change host ip address. Why they want this is beyond me.
