### ISSUE TITLE
Wrong error for Ubuntu 18.04

### ISSUE THREAD

**Issue by digininja** [Raikia/FiercePhish#65]
I thought I'd try the automatic installer on 18.04 but got this error:

```
   [~] Detecting OS distribution...
   [!] You are running Ubuntu 18.04. This is not supported by this installer. There's really no reason to not update Ubuntu
```

Just to be picky, I have updated!

I gave up with trying to push through with the automated installer and went back to a 16.04 box, I could probably have got it working but didn't have the time.

**Comment by Raikia** [comment]
Funny that I stopped supporting new versions of Ubuntu when I started working on v2.0.  I agree that is silly and I will fix this.  Thanks for the report.

**Comment by Raikia** [comment]
Fixed finally
