### ISSUE TITLE
How to use after installed FiercePhish ?

### ISSUE THREAD

**Issue by xtlyn** [Raikia/FiercePhish#76]
When i'am installed FiercePhish ,it told me to  go to http://124.204.60.98:8080/ to use FiercePhish! but I can't use it ,I assume there is a config I need to set somewhere but don't know where, any ideas?

**Comment by Raikia** [comment]
Have you tried turning it off and on again?

**Comment by TheThingGoesSkra** [comment]
I have the same problem. I tried turning it off and on again, but nothing change. All the services are running and when i go to 127.0.0.1:80 my browser display the php code of /var/www/fiercephishing/public/index.php. Can you help me plz ?
