### ISSUE TITLE
Add inbox

### ISSUE THREAD

**Issue by Raikia** [Raikia/FiercePhish#8]
Add functionality to receive email (by connecting to an IMAP server), and reply to the emails.

**Comment by GitHipster** [comment]
A 'catch all' mailbox would be nice to prevent lots of undeliverable out of office notifications when using a false source mail address.

**Comment by Raikia** [comment]
That's what this will be.  The installer already sets up imap (dovecot) with this configuration, so it's just a matter of writing the background jobs to grab mail and the UI to display it.

**Comment by Raikia** [comment]
This was included in the [v1.2.0 release](https://github.com/Raikia/FiercePhish/releases/tag/v1.2.0).  Issue resolved.
