### ISSUE TITLE
Deleteing data or re-initializing database

### ISSUE THREAD

**Issue by housemusic42** [Raikia/FiercePhish#88]
Hello,

Trying to delete emails and campaigns and when I couldn't locate anything I tried to delete data out of the DB tables. The app does not like this and I end up re-installing. 

I'll keep poking around but looking for a good way to remove data and start fresh without performing a full re-install. I'll try and get more familiar with the technologies you're using for this platform but I love it!

Thanks!

**Comment by Raikia** [comment]
FP isn't intended to support data deletion because that can cause issues in the logs with various references.  It's generally recommended to keep old data or spin up a new instance
